
// <auto-generated />
namespace EBillingWeb {
    public partial class Bills {
        protected global::System.Web.UI.WebControls.TextBox txtCount;
        protected global::System.Web.UI.WebControls.Button btnPrepare;
        protected global::System.Web.UI.WebControls.Label lblPrepMsg;
        protected global::System.Web.UI.WebControls.PlaceHolder phRows;
        protected global::System.Web.UI.WebControls.Button btnSaveAll;
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.TextBox txtLastN;
        protected global::System.Web.UI.WebControls.Button btnFetch;
        protected global::System.Web.UI.WebControls.GridView grdBills;
    }
}
