
// <auto-generated />
namespace EBillingWeb {
    public partial class BillPrint {
        protected global::System.Web.UI.WebControls.Label lblCno;
        protected global::System.Web.UI.WebControls.Label lblCname;
        protected global::System.Web.UI.WebControls.Label lblUnits;
        protected global::System.Web.UI.WebControls.Label lblAmount;
    }
}
