
// <auto-generated />
namespace EBillingWeb {
    public partial class Reports {
        protected global::System.Web.UI.WebControls.TextBox txtN;
        protected global::System.Web.UI.WebControls.Button btnGo;
        protected global::System.Web.UI.WebControls.GridView grid;
    }
}
