
// <auto-generated />
namespace EBillingWeb {
    public partial class SiteMaster {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder TitleContent;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
